### ISSUE TITLE
Making an iron pickaxe when you're on the MAKE_IRON_PICKAXE objective doesn't do anything

### ISSUE THREAD

**Issue by its-c10** [nthByte-LLC/iron-craft#6]

**Comment by LBrinkmann** [comment]
I created all other items with the recipe book, only the iron pickaxe I created just placing the resources at the right spot on the crafting table (the 3x3 grid). 

Also, in the same game i created, by mistake, the stone pickaxe too early according the the objectives. So I had to create a second one to proceed. But that did seemed  to be problematic. Would not call that a bug, just wanted to mention in case it could be related to the later hick-up.
